FROM ubuntu:18.04
FROM continuumio/miniconda:latest

# Create a working directory
RUN mkdir wd
WORKDIR /wd/

# Copy everything
COPY . /wd/

#Setting shell to bash
SHELL ["/bin/bash", "-c"]
# Create conda enviroment using the yml file
RUN conda env create -f modtran_env.yml

# Activate conda environment
#ENV PATH /opt/conda/envs/modtran_env/bin
# Initialise conda and activate the environment 
RUN echo "conda activate modtran_env" >> ~/.bashrc
ENV PATH $PATH:/opt/conda/envs/modtran_env/bin
# Command to run dashboard script
CMD [ "gunicorn", "--workers=5", "--threads=1", "-b 0.0.0.0:8000", "dash-modtran:server"]
